- name: DOCKER - Uninstall old versions
  become: true
  dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ pkgs_remove_docker }}"
- name: DOCKER - Add Repository
  become: true
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- name: DOCKER - Install latest version
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs_docker }}"
- name: DOCKER - Start service
  become: true
  systemd_service:
    name: docker
    enabled: true
    state: started
- name: DOCKER - Create docker group
  become: true
  group:
    name: docker
    state: present
- name: DOCKER - Add user to docker group
  become: true
  user:
    name: wgonzalez
    groups: docker
    append: true
